import pandas as pd
from utils import PreprocessData
import numpy as np
from load_data import LoadData

api_key = 'RGAPI-3ec05947-04f7-4650-a49a-0c4b0e5d1b1f'

test = PreprocessData('./api_data/api_match_info.json', './api_data/api_timeline_info.json')

load_instance = LoadData(api_key)
# 데이터 가져오기
interval_list = test.get_condition_timeline(10000)
#interval_list = test.get_event()
#interval_list, get_win_lose_list = load_instance.get_summoner_data_list(1)

interval_list = np.array(interval_list, dtype=int)


# 헤더 정의
n = [
    "TIMESTAMP",
    "TEAM1_TOP_CHAMPION", "TEAM1_TOP_GOLD", "TEAM1_TOP_ITEM_GOLD", "TEAM1_TOP_POTION",
    "TEAM1_TOP_K", "TEAM1_TOP_D", "TEAM1_TOP_A",
    "TEAM1_TOP_STATPERK_DEFENCE", "TEAM1_TOP_STATPERK_FLEX", "TEAM1_TOP_STATPERK_OFFENSE",
    "TEAM1_TOP_PRIMARY1", "TEAM1_TOP_PRIMARY2", "TEAM1_TOP_PRIMARY3", "TEAM1_TOP_PRIMARY4",
    "TEAM1_TOP_SUBSTYLE1", "TEAM1_TOP_SUBSTYLE2",
    "TEAM1_JUNGLE_CHAMPION", "TEAM1_JUNGLE_GOLD", "TEAM1_JUNGLE_ITEM_GOLD", "TEAM1_JUNGLE_POTION",
    "TEAM1_JUNGLE_K", "TEAM1_JUNGLE_D", "TEAM1_JUNGLE_A",
    "TEAM1_JUNGLE_STATPERK_DEFENCE", "TEAM1_JUNGLE_STATPERK_FLEX", "TEAM1_JUNGLE_STATPERK_OFFENSE",
    "TEAM1_JUNGLE_PRIMARY1", "TEAM1_JUNGLE_PRIMARY2", "TEAM1_JUNGLE_PRIMARY3", "TEAM1_JUNGLE_PRIMARY4",
    "TEAM1_JUNGLE_SUBSTYLE1", "TEAM1_JUNGLE_SUBSTYLE2",
    "TEAM1_MIDDLE_CHAMPION", "TEAM1_MIDDLE_GOLD", "TEAM1_MIDDLE_ITEM_GOLD", "TEAM1_MIDDLE_POTION",
    "TEAM1_MIDDLE_K", "TEAM1_MIDDLE_D", "TEAM1_MIDDLE_A",
    "TEAM1_MIDDLE_STATPERK_DEFENCE", "TEAM1_MIDDLE_STATPERK_FLEX", "TEAM1_MIDDLE_STATPERK_OFFENSE",
    "TEAM1_MIDDLE_PRIMARY1", "TEAM1_MIDDLE_PRIMARY2", "TEAM1_MIDDLE_PRIMARY3", "TEAM1_MIDDLE_PRIMARY4",
    "TEAM1_MIDDLE_SUBSTYLE1", "TEAM1_MIDDLE_SUBSTYLE2",
    "TEAM1_BOTTOM_CHAMPION", "TEAM1_BOTTOM_GOLD", "TEAM1_BOTTOM_ITEM_GOLD", "TEAM1_BOTTOM_POTION",
    "TEAM1_BOTTOM_K", "TEAM1_BOTTOM_D", "TEAM1_BOTTOM_A",
    "TEAM1_BOTTOM_STATPERK_DEFENCE", "TEAM1_BOTTOM_STATPERK_FLEX", "TEAM1_BOTTOM_STATPERK_OFFENSE",
    "TEAM1_BOTTOM_PRIMARY1", "TEAM1_BOTTOM_PRIMARY2", "TEAM1_BOTTOM_PRIMARY3", "TEAM1_BOTTOM_PRIMARY4",
    "TEAM1_BOTTOM_SUBSTYLE1", "TEAM1_BOTTOM_SUBSTYLE2",
    "TEAM1_UTILITY_CHAMPION", "TEAM1_UTILITY_GOLD", "TEAM1_UTILITY_ITEM_GOLD", "TEAM1_UTILITY_POTION",
    "TEAM1_UTILITY_K", "TEAM1_UTILITY_D", "TEAM1_UTILITY_A",
    "TEAM1_UTILITY_STATPERK_DEFENCE", "TEAM1_UTILITY_STATPERK_FLEX", "TEAM1_UTILITY_STATPERK_OFFENSE",
    "TEAM1_UTILITY_PRIMARY1", "TEAM1_UTILITY_PRIMARY2", "TEAM1_UTILITY_PRIMARY3", "TEAM1_UTILITY_PRIMARY4",
    "TEAM1_UTILITY_SUBSTYLE1", "TEAM1_UTILITY_SUBSTYLE2",
    "TEAM1_GOLD",
    "WARD_PLACED", "WARD_KILL", "HORDE_COUNT", "DRAGON_COUNT", "RIFTHERALD_COUNT", "BARON_NASHOR_COUNT",
    "TOWER_TOP_COUNT", "TOWER_MIDDLE_COUNT", "TOWER_BOTTOM_COUNT",
    "TEAM2_TOP_CHAMPION", "TEAM2_TOP_GOLD", "TEAM2_TOP_ITEM_GOLD", "TEAM2_TOP_POTION",
    "TEAM2_TOP_K", "TEAM2_TOP_D", "TEAM2_TOP_A",
    "TEAM2_TOP_STATPERK_DEFENCE", "TEAM2_TOP_STATPERK_FLEX", "TEAM2_TOP_STATPERK_OFFENSE",
    "TEAM2_TOP_PRIMARY1", "TEAM2_TOP_PRIMARY2", "TEAM2_TOP_PRIMARY3", "TEAM2_TOP_PRIMARY4",
    "TEAM2_TOP_SUBSTYLE1", "TEAM2_TOP_SUBSTYLE2",
    "TEAM2_JUNGLE_CHAMPION", "TEAM2_JUNGLE_GOLD", "TEAM2_JUNGLE_ITEM_GOLD", "TEAM2_JUNGLE_POTION",
    "TEAM2_JUNGLE_K", "TEAM2_JUNGLE_D", "TEAM2_JUNGLE_A",
    "TEAM2_JUNGLE_STATPERK_DEFENCE", "TEAM2_JUNGLE_STATPERK_FLEX", "TEAM2_JUNGLE_STATPERK_OFFENSE",
    "TEAM2_JUNGLE_PRIMARY1", "TEAM2_JUNGLE_PRIMARY2", "TEAM2_JUNGLE_PRIMARY3", "TEAM2_JUNGLE_PRIMARY4",
    "TEAM2_JUNGLE_SUBSTYLE1", "TEAM2_JUNGLE_SUBSTYLE2",
    "TEAM2_MIDDLE_CHAMPION", "TEAM2_MIDDLE_GOLD", "TEAM2_MIDDLE_ITEM_GOLD", "TEAM2_MIDDLE_POTION",
    "TEAM2_MIDDLE_K", "TEAM2_MIDDLE_D", "TEAM2_MIDDLE_A",
    "TEAM2_MIDDLE_STATPERK_DEFENCE", "TEAM2_MIDDLE_STATPERK_FLEX", "TEAM2_MIDDLE_STATPERK_OFFENSE",
    "TEAM2_MIDDLE_PRIMARY1", "TEAM2_MIDDLE_PRIMARY2", "TEAM2_MIDDLE_PRIMARY3", "TEAM2_MIDDLE_PRIMARY4",
    "TEAM2_MIDDLE_SUBSTYLE1", "TEAM2_MIDDLE_SUBSTYLE2",
    "TEAM2_BOTTOM_CHAMPION", "TEAM2_BOTTOM_GOLD", "TEAM2_BOTTOM_ITEM_GOLD", "TEAM2_BOTTOM_POTION",
    "TEAM2_BOTTOM_K", "TEAM2_BOTTOM_D", "TEAM2_BOTTOM_A",
    "TEAM2_BOTTOM_STATPERK_DEFENCE", "TEAM2_BOTTOM_STATPERK_FLEX", "TEAM2_BOTTOM_STATPERK_OFFENSE",
    "TEAM2_BOTTOM_PRIMARY1", "TEAM2_BOTTOM_PRIMARY2", "TEAM2_BOTTOM_PRIMARY3", "TEAM2_BOTTOM_PRIMARY4",
    "TEAM2_BOTTOM_SUBSTYLE1", "TEAM2_BOTTOM_SUBSTYLE2",
    "TEAM2_UTILITY_CHAMPION", "TEAM2_UTILITY_GOLD", "TEAM2_UTILITY_ITEM_GOLD", "TEAM2_UTILITY_POTION",
    "TEAM2_UTILITY_K", "TEAM2_UTILITY_D", "TEAM2_UTILITY_A",
    "TEAM2_UTILITY_STATPERK_DEFENCE", "TEAM2_UTILITY_STATPERK_FLEX", "TEAM2_UTILITY_STATPERK_OFFENSE",
    "TEAM2_UTILITY_PRIMARY1", "TEAM2_UTILITY_PRIMARY2", "TEAM2_UTILITY_PRIMARY3", "TEAM2_UTILITY_PRIMARY4",
    "TEAM2_UTILITY_SUBSTYLE1", "TEAM2_UTILITY_SUBSTYLE2",
    "TEAM2_GOLD",
    "WARD_PLACED", "WARD_KILL", "HORDE_COUNT", "DRAGON_COUNT", "RIFTHERALD_COUNT", "BARON_NASHOR_COUNT",
    "TOWER_TOP_COUNT", "TOWER_MIDDLE_COUNT", "TOWER_BOTTOM_COUNT",
    
]


# DataFrame 생성
# df = pd.DataFrame(data=interval_list, columns=n)

# interval_list를 2차원 배열로 변환
interval_list_2d = np.array(interval_list).reshape(-1, len(n))

# DataFrame 생성
df = pd.DataFrame(data=interval_list_2d, columns=n)


#df = pd.DataFrame(data=interval_list)


# DataFrame을 엑셀 파일로 저장
df.to_excel("log.xlsx", index=False)